# This device has 2 nano SIM slots. So, enable ril_0 (SIM 1) and ril_1 (SIM 2)
[Settings]
ExpectSlots = slot1,slot2
extPlugin = qti
radioInterface = 1.5

[slot1]
path = /ril_0
slot = 0

[slot2]
path = /ril_1
slot = 1
