name: Build flashable test

on:
  workflow_dispatch:

jobs:
    flashable:
        runs-on: ubuntu-22.04
        env:
            ADAPTATION_TOOLS_BRANCH: main

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup build environment
              run: |
                  sudo apt update
                  sudo apt install bc bison build-essential ca-certificates cpio curl fakeroot flex git img2simg jq kmod libssl-dev libtinfo5 lz4 python2 python3 sudo unzip wget xz-utils -y --no-install-recommends
                  sudo ln -sf python2 /usr/bin/python
                  sudo wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg

            - name: Patch Kernel Configuration to Fix Memory Conflict
              run: |
                  # The configuration file path is arch/arm64/configs/defconfig
                  DEFCONFIG_PATH="arch/arm64/configs/defconfig" 
                  
                  # Inject CONFIG_PHYS_OFFSET=0x80000000 to move the kernel load address.
                  # This high address should bypass the hardware's reserved memory range (0x2700000 - 0x3588fff).
                  echo "CONFIG_PHYS_OFFSET=0x0000000080000000" >> $DEFCONFIG_PATH
                  
                  echo "Successfully patched $DEFCONFIG_PATH with CONFIG_PHYS_OFFSET."
                  
            - name: Build device tarball
              run: |
                  git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b $ADAPTATION_TOOLS_BRANCH build
                  ./build.sh

            - name: Build devel-flashable
              run: |
                  DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
                  ./build/fetch-and-prepare-latest-ota.sh "20.04/arm64/android9plus/devel" "$DEVICE" ota
                  mkdir -p out
                  ./build/system-image-from-ota.sh ota/ubuntu_command out

            - name: Upload boot image to artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: bootimage
                  path: out/boot.img
                  if-no-files-found: error

            - name: Upload vendor_boot image to artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: vendor_bootimage
                  path: out/vendor_boot.img
                  if-no-files-found: error

            - name: Upload system image to artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: systemimage
                  path: out/system.img
                  if-no-files-found: error
